/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCompararRouteImport } from './routes/app.comparar'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppOportunidadesRouteImport } from './routes/app.oportunidades'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppScoreRouteImport } from './routes/app.score'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompararRoute = AppCompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppScoreRoute = AppScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/comparar': typeof AppCompararRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/score': typeof AppScoreRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/comparar': typeof AppCompararRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/score': typeof AppScoreRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/comparar': typeof AppCompararRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/score': typeof AppScoreRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/comparar'
    | '/app/configuracoes'
    | '/app/oportunidades'
    | '/app/relatorios'
    | '/app/score'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/comparar'
    | '/app/configuracoes'
    | '/app/oportunidades'
    | '/app/relatorios'
    | '/app/score'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/comparar'
    | '/app/configuracoes'
    | '/app/oportunidades'
    | '/app/relatorios'
    | '/app/score'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparar': {
      id: '/app/comparar'
      path: '/comparar'
      fullPath: '/app/comparar'
      preLoaderRoute: typeof AppCompararRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidades': {
      id: '/app/oportunidades'
      path: '/oportunidades'
      fullPath: '/app/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/score': {
      id: '/app/score'
      path: '/score'
      fullPath: '/app/score'
      preLoaderRoute: typeof AppScoreRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompararRoute: typeof AppCompararRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppScoreRoute: typeof AppScoreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompararRoute: AppCompararRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppScoreRoute: AppScoreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
